association/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.contrib.auth import views as auth_views
#from rest_framework.urlpatterns import format_suffix_patterns
from gestion import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gestion/', include('gestion.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'gestion'

urlpatterns = [

    # Administration
    url(r'^admin/', admin.site.urls),

    # Gestion
    url(r'^$', views.index, name='index'),
    url(r'^acceuil/$', views.acceuil, name='acceuil'),
    url(r'^déconnexion/$', views.logout_user, name='logout'),


    # Add, Update, Delete Medicament URLS
    url(r'^clients/$', views.ClientList.as_view(), name='client_list'),
    url(r'^creer_client/$', views.ClientCreate.as_view(), name='client_create'),
    url(r'^modifier_client/(?P<pk>\d+)/$', views.ClientUpdate.as_view(), name='client_update'),
    url(r'^supprimer_client/(?P<pk>\d+)/$', views.ClientDelete.as_view(), name='client_delete'),
    url(r'^detail_client/(?P<pk>\d+)/$', views.ClientDetailView.as_view(), name='detail_client'),


    # Add, Update, Delete Medicament URLS
    url(r'^comptes/$', views.CompteList.as_view(), name='compte_list'),
    url(r'^creer_compte/$', views.CompteCreate.as_view(), name='compte_create'),
    url(r'^modifier_compte/(?P<pk>\d+)/$', views.CompteUpdate.as_view(), name='compte_update'),
    url(r'^supprimer_compte/(?P<pk>\d+)/$', views.CompteDelete.as_view(), name='compte_delete'),
    url(r'^detail_compte/(?P<pk>\d+)/$', views.CompteDetailView.as_view(), name='detail_compte'),


]

gestion/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Client, TypeClient, Compte
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import StrictButton
from crispy_forms.layout import Layout
from crispy_forms.bootstrap import TabHolder, Tab

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        exclude = ['created_at', 'updated_at', 'ajoute_par']


class TypeClientForm(forms.ModelForm):

    class Meta:
        model = TypeClient
        fields = ['libelle', 'description']


class ClientForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """
        Surcharge de l'initialisation du formulaire
        """
        super().__init__(*args, **kwargs)
        # Tu utilises FormHelper pour customiser ton formulaire
        self.helper = FormHelper()
        # Tu définis l'id et la classe bootstrap de ton formulaire
        self.helper.form_class = 'form-horizontal'
        self.helper.form_id = 'client-form'
        # Tu définis la taille des labels et des champs sur la grille
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-8'
        # Tu crées l'affichage de ton formulaire
        self.helper.layout = Layout(
            # Le formulaire va contenir 3 onglets
            TabHolder(
                # Premier onglet
                Tab(
                    # Label de l'onglet
                    'Général',
                    # Liste des champs du modèle à afficher dans l'onglet
                    'noms',
                    'prenoms',
                    'datenaissance',
                    'photo',
                    # Tu rajoutes un bouton "Suivant"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-right" \
                        aria-hidden="true"></span> %s' % "Suivant",
                        type='button',
                        css_class='btn-warning col-md-offset-9 btnNext',
                    )

                ),
                # Deuxième onglet
                Tab(
                    # Label de l'onglet
                    'Informations',
                    # Liste des champs à afficher
                    'typeclient',
                    'email',
                    'phone',
                    'profession',
                    # Tu rajoutes des boutons "Précédent" et "Suivant"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-left" \
                        aria-hidden="true"></span> %s' % 'Précédent',
                        type='button',
                        css_class='btn-primary btnPrevious',
                    ),
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-right" \
                        aria-hidden="true"></span> %s' % 'Suivant',
                        type='button',
                        css_class='btn-warning col-md-offset-8 btnNext',
                    )
                ),
                # Troisième onglet
                Tab(
                    # Label de l'onglet
                    'Autres',
                    # Liste des champs à afficher dont les champs supplémentaires
                    'adresse',
                    'ville',
                    'nationalite',
                    'quartier',
                    # Tu rajoutes des boutons "Précédent" et "Valider"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-left" \
                        aria-hidden="true"></span> %s' % "Précédent",
                        type='button',
                        css_class='btn-warning btnPrevious',
                    ),
                    StrictButton(
                        '<span class="glyphicon glyphicon-ok" \
                        aria-hidden="true"></span> %s' % "Valider",
                        type='submit',
                        css_class='btn-success col-md-offset-8'
                    )
                ),
            ),
        )

    class Meta:
        # Tu définis le modèle utilisé
        model = Client
        exclude = ['created_at', 'updated_at', 'ajoute_par']



class CompteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """
        Surcharge de l'initialisation du formulaire
        """
        super().__init__(*args, **kwargs)
        # Tu utilises FormHelper pour customiser ton formulaire
        self.helper = FormHelper()
        # Tu définis l'id et la classe bootstrap de ton formulaire
        self.helper.form_class = 'form-horizontal'
        self.helper.form_id = 'compte-form'
        # Tu définis la taille des labels et des champs sur la grille
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-8'
        # Tu crées l'affichage de ton formulaire
        self.helper.layout = Layout(
            # Le formulaire va contenir 3 onglets
            TabHolder(
                # Premier onglet
                Tab(
                    # Label de l'onglet
                    'Compte',
                    # Liste des champs du modèle à afficher dans l'onglet
                    'typecompte',
                    'numero',
                    'ouverture',
                    'cloture',
                    # Tu rajoutes un bouton "Suivant"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-right" \
                        aria-hidden="true"></span> %s' % "Suivant",
                        type='button',
                        css_class='btn-warning col-md-offset-9 btnNext',
                    )

                ),
                # Deuxième onglet
                Tab(
                    # Label de l'onglet
                    'Conditions arrêtées',
                    # Liste des champs à afficher
                    'intitule',
                    'statut',
                    'matricule',
                    'montancartone',
                    # Tu rajoutes des boutons "Précédent" et "Suivant"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-left" \
                        aria-hidden="true"></span> %s' % 'Précédent',
                        type='button',
                        css_class='btn-primary btnPrevious',
                    ),
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-right" \
                        aria-hidden="true"></span> %s' % 'Suivant',
                        type='button',
                        css_class='btn-warning col-md-offset-8 btnNext',
                    )
                ),
                # Troisième onglet
                Tab(
                    # Label de l'onglet
                    'Autres',
                    # Liste des champs à afficher dont les champs supplémentaires
                    'numcpte',
                    'decouvertauto',
                    'debut',
                    'fin',
                    # Tu rajoutes des boutons "Précédent" et "Valider"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-left" \
                        aria-hidden="true"></span> %s' % "Précédent",
                        type='button',
                        css_class='btn-warning btnPrevious',
                    ),
                    StrictButton(
                        '<span class="glyphicon glyphicon-ok" \
                        aria-hidden="true"></span> %s' % "Valider",
                        type='submit',
                        css_class='btn-success col-md-offset-8'
                    )
                ),
            ),
        )

    class Meta:
        # Tu définis le modèle utilisé
        model = Compte
        exclude = ['created_at', 'updated_at', 'ajoute_par']

gestion/views.py
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.forms import ModelForm
from .forms import UserForm, ClientForm, TypeClientForm, CompteForm
import re
from django.db.models import Q

from .models import Client, Compte

# Create your views here.



def index(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('gestion:acceuil')
			else:
				return render(request, 'gestion/pages/index.html', {'error_message': 'Votre compte a été désactivé'})
		else:
			return render(request, 'gestion/pages/index.html', {'error_message': 'Paramètres Invalides'})
	return render(request, 'gestion/pages/index.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('gestion:index')



def acceuil(request):
	return render(request, 'gestion/pages/acceuil.html', {})



# Medicament CRUD
class ClientList(ListView):
	model = Client

class ClientCreate(CreateView):
	model = Client
	form_class = ClientForm
	success_url = reverse_lazy('gestion:client_list')

class ClientUpdate(UpdateView):
	model = Client
	form_class = ClientForm
	success_url = reverse_lazy('gestion:client_list')

class ClientDelete(DeleteView):
	model = Client
	success_url = reverse_lazy('gestion:client_list')

class ClientDetailView(DetailView):

    model = Client
    success_url = reverse_lazy('gestion:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



# Medicament CRUD
class CompteList(ListView):
	model = Compte

class CompteCreate(CreateView):
	model = Compte
	form_class = CompteForm
	success_url = reverse_lazy('gestion:compte_list')

class CompteUpdate(UpdateView):
	model = Compte
	form_class = CompteForm
	success_url = reverse_lazy('gestion:compte_list')

class CompteDelete(DeleteView):
	model = Compte
	success_url = reverse_lazy('gestion:compte_list')

class CompteDetailView(DetailView):

    model = Compte
    success_url = reverse_lazy('gestion:compte_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

gestion/templates/gestion/client_confirm_delete.html
{% extends 'gestion/pages/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Supprimer un Client{% endblock %}

{% block content %}

    <div class="page-content-wrapper ">

        <div class="container-fluid">


            <div class="card">
                <div class="card-body">

                    <h3 class="text-center mt-0 m-b-15">
                        <a href="" class="logo logo-admin"><!--img src="" height="54" alt="logo"--></a>
                    </h3>

                    <h4 class="text-muted text-center font-18"><b>Supprimer un Client</b></h4>

                    <form class="form-horizontal" method="POST">
                      {% csrf_token %}
                      <div class="box-body">
                        <div class="form-group">
                          <div class="col-sm-10">
                            <p>Etes-vous sûr de vouloir supprimer <a href="#">{{ object }}</a>?</p>
                          </div>
                        </div>
                      </div>
                      <!-- /.box-body -->
                      <div class="box-footer">
                        <a href="{% url 'gestion:client_list' %}" type="submit" class="btn btn-primary">Annuler et retourner vers la liste</a>
                        <input type="submit" class="btn btn-danger pull-right" value="Supprimer">
                      </div>
                      <!-- /.box-footer -->
                    </form>

                </div>
            </div>
            
        </div>

    </div>










{% endblock %}


{% block title_footer %}Supprimer un Client{% endblock %}

gestion/templates/gestion/client_detail.html
{% extends 'gestion/pages/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Détail Client{% endblock %}

{% block content %}

    <div class="page-content-wrapper ">

                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <div class="media">
                                                <img class="d-flex mr-3 rounded-circle img-thumbnail thumb-lg" src="{{ object.photo.url }}" alt="Generic placeholder image">
                                                <div class="media-body">
                                                    <h5 class="mt-0 font-18 mb-1">{{ object.nom }} {{ object.prenoms }}</h5>
                                                    <p class="text-muted font-14">{{ object.profession }}</p>

                                                    

                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div> <!-- end col -->


                            </div> <!-- end row -->

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Client N°/ {{ object.id }}</h4>

                                            <!-- Nav tabs -->
                                            <ul class="nav nav-tabs" role="tablist">
                                                <li class="nav-item">
                                                    <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Mes infos</a>
                                                </li>
                                            </ul>

                                            <!-- Tab panes -->
                                            <div class="tab-content">
                                                <div class="tab-pane active p-3" id="home" role="tabpanel">
                                                    <p class="font-14 mb-0">
                                                        <strong>Type Client :</strong><br> {{ object.typeclient }}<br>
                                                        <strong>Noms & Prénoms :</strong><br> {{ object.nom }} {{ object.prenoms }}.<br>
                                                        <strong>Email :</strong><br> {{ object.email }}<br>
                                                        <strong>Téléphone :</strong><br> (+241) {{ object.phone }}<br>
                                                        <strong>Adresse :</strong><br> {{ object.adresse }}.<br>
                                                        <strong>Date de Naissance :</strong><br> {{ object.datenaissance }}.<br>
                                                        <strong>Profession :</strong><br> {{ object.profession }}.<br>
                                                        <strong>Nationalité :</strong><br> {{ object.nationalite }}.<br>
                                                        <strong>Ville :</strong><br> {{ object.ville }}.<br>
                                                        <strong>Quartier :</strong><br> {{ object.quartier }}.<br>
                                                    </p>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>


                            </div> <!-- end row -->



                        </div><!-- container-fluid -->


                    </div> <!-- Page content Wrapper -->










{% endblock %}


{% block title_footer %}Détail Client{% endblock %}

gestion/templates/gestion/client_form.html
{% extends 'gestion/pages/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Créer un Client{% endblock %}

{% block content %}

    <div class="page-content-wrapper ">

        <div class="container-fluid">


            <div class="card">
                <div class="card-body">

                    <h3 class="text-center mt-0 m-b-15">
                        <a href="" class="logo logo-admin"><!--img src="" height="54" alt="logo"--></a>
                    </h3>

                    <h4 class="text-muted text-center font-18"><b>Créer un Client</b></h4>

                    <div class="p-3">
                        {% crispy form %}
                    </div>

                </div>
            </div>
            
        </div>

    </div>










{% endblock %}


{% block title_footer %}Créer un Client{% endblock %}

gestion/templates/gestion/client_list.html
{% extends 'gestion/pages/base.html' %}

{% block title %}Liste des Clients{% endblock %}

{% block content %}


            <div class="page-content-wrapper ">

                    <div class="box-footer">
                        <a href="{% url 'gestion:client_create' %}" class="btn btn-primary">Ajouter un Client</a>
                    </div><br>


                        <div class="row">

                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">
                                            <h4 class="mt-0 m-b-15 header-title"> <span class="badge badge-primary"></span>Liste des Clients </h4>
                                            <div class="table-responsive">
                                                <table class="table table-hover m-b-0">
                                                    <thead>
                                                    <tr>
                                                        <th>Id</th>
                                                        <th>Noms</th>
                                                        <th>Prénoms</th>
                                                        <th>Adresse</th>
                                                        <th>Téléphone</th>
                                                        <th>Type Client</th>
                                                        <th>Date Création</th>
                                                        <th>Actions</th>
                                                    </tr>

                                                    </thead>
                                                    <tbody>
                                                    {% for client in client_list %}
                                                      <tr>
                                                        <td>
                                                          <a href="{% url 'gestion:client_update' client.id %}">
                                                           {{ client.id }} 
                                                          </a>
                                                        </td>
                                                        <td>{{ client.noms }}</td>
                                                        <td>{{ client.prenoms }}</td>
                                                        <td>{{ client.adresse }}</td>
                                                        <td>{{ client.phone }}</td>
                                                        <td>{{ client.typeclient }}</td>
                                                        <td>{{ client.datenaissance }}</td>
                                                        <td>
                                                          <div class="btn-group" role="group" aria-label="...">
                                                            <a href="{% url 'gestion:client_update' client.id %}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                            <a href="{% url 'gestion:detail_client' client.id %}" class="btn btn-warning"><i class="fa fa-eye"></i></a>
                                                            <a href="{% url 'gestion:client_delete' client.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                                          </div>
                                                        </td>
                                                      </tr>
                                                   {% endfor %}

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- end row -->


                    </div> <!-- Page content Wrapper --> 










{% endblock %}


{% block title_footer %}Liste des Clients{% endblock %}

gestion/templates/gestion/compte_confirm_delete.html
{% extends 'gestion/pages/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Supprimer un Compte{% endblock %}

{% block content %}

    <div class="page-content-wrapper ">

        <div class="container-fluid">


            <div class="card">
                <div class="card-body">

                    <h3 class="text-center mt-0 m-b-15">
                        <a href="" class="logo logo-admin"><!--img src="" height="54" alt="logo"--></a>
                    </h3>

                    <h4 class="text-muted text-center font-18"><b>Supprimer un Compte</b></h4>

                    <form class="form-horizontal" method="POST">
                      {% csrf_token %}
                      <div class="box-body">
                        <div class="form-group">
                          <div class="col-sm-10">
                            <p>Etes-vous sûr de vouloir supprimer <a href="#">{{ object }}</a>?</p>
                          </div>
                        </div>
                      </div>
                      <!-- /.box-body -->
                      <div class="box-footer">
                        <a href="{% url 'gestion:compte_list' %}" type="submit" class="btn btn-primary">Annuler et retourner vers la liste</a>
                        <input type="submit" class="btn btn-danger pull-right" value="Supprimer">
                      </div>
                      <!-- /.box-footer -->
                    </form>

                </div>
            </div>
            
        </div>

    </div>










{% endblock %}


{% block title_footer %}Supprimer un Client{% endblock %}

gestion/templates/gestion/compte_form.html
{% extends 'gestion/pages/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Créer un Compte{% endblock %}

{% block content %}

    <div class="page-content-wrapper ">

        <div class="container-fluid">


            <div class="card">
                <div class="card-body">

                    <h3 class="text-center mt-0 m-b-15">
                        <a href="" class="logo logo-admin"><!--img src="" height="54" alt="logo"--></a>
                    </h3>

                    <h4 class="text-muted text-center font-18"><b>Créer un Compte</b></h4>

                    <div class="p-3">
                        {% crispy form %}
                    </div>

                </div>
            </div>
            
        </div>

    </div>










{% endblock %}


{% block title_footer %}Créer un Compte{% endblock %}

gestion/templates/gestion/compte_list.html
{% extends 'gestion/pages/base.html' %}

{% block title %}Liste des Comptes{% endblock %}

{% block content %}


            <div class="page-content-wrapper ">

                    <div class="box-footer">
                        <a href="{% url 'gestion:compte_create' %}" class="btn btn-primary">Ajouter un Compte</a>
                    </div><br>


                        <div class="row">

                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">
                                            <h4 class="mt-0 m-b-15 header-title"> <span class="badge badge-primary"></span>Liste des Comptes </h4>
                                            <div class="table-responsive">
                                                <table class="table table-hover m-b-0">
                                                    <thead>
                                                    <tr>
                                                        <th>Id</th>
                                                        <th>Nature</th>
                                                        <th>Cpte Général</th>
                                                        <th>Intitulé</th>
                                                        <th>Statut</th>
                                                        <th>Montant Cartoné</th>
                                                        <th>Cpte Intérêts</th>
                                                        <th>Actions</th>
                                                    </tr>

                                                    </thead>
                                                    <tbody>
                                                    {% for compte in compte_list %}
                                                      <tr>
                                                        <td>
                                                          <a href="{% url 'gestion:compte_update' compte.id %}">
                                                           {{ compte.id }} 
                                                          </a>
                                                        </td>
                                                        <td>{{ compte.typecompte }}</td>
                                                        <td>{{ compte.numero }}</td>
                                                        <td>{{ compte.intitule }}</td>
                                                        <td>{{ compte.statut }}</td>
                                                        <td>{{ compte.montancartone }}</td>
                                                        <td>{{ compte.numcpte }}</td>
                                                        <td>
                                                          <div class="btn-group" role="group" aria-label="...">
                                                            <a href="{% url 'gestion:compte_update' compte.id %}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                            <a href="{% url 'gestion:detail_compte' compte.id %}" class="btn btn-warning"><i class="fa fa-eye"></i></a>
                                                            <a href="{% url 'gestion:compte_delete' compte.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                                          </div>
                                                        </td>
                                                      </tr>
                                                   {% endfor %}

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- end row -->


                    </div> <!-- Page content Wrapper --> 










{% endblock %}


{% block title_footer %}Liste des Comptes{% endblock %}