association/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.contrib.auth import views as auth_views
#from rest_framework.urlpatterns import format_suffix_patterns
from gestion import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gestion/', include('gestion.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'gestion'

urlpatterns = [

    # Administration
    url(r'^admin/', admin.site.urls),

    # Gestion
    url(r'^$', views.index, name='index'),
    url(r'^acceuil/$', views.acceuil, name='acceuil'),
    url(r'^déconnexion/$', views.logout_user, name='logout'),


    # Add, Update, Delete Medicament URLS
    url(r'^clients/$', views.ClientList.as_view(), name='client_list'),
    url(r'^creer_client/$', views.ClientCreate.as_view(), name='client_create'),
    url(r'^modifier_client/(?P<pk>\d+)/$', views.ClientUpdate.as_view(), name='client_update'),
    url(r'^supprimer_client/(?P<pk>\d+)/$', views.ClientDelete.as_view(), name='client_delete'),
    url(r'^detail_client/(?P<pk>\d+)/$', views.ClientDetailView.as_view(), name='detail_client'),


    # Add, Update, Delete Medicament URLS
    url(r'^comptes/$', views.CompteList.as_view(), name='compte_list'),
    url(r'^creer_compte/$', views.CompteCreate.as_view(), name='compte_create'),
    url(r'^modifier_compte/(?P<pk>\d+)/$', views.CompteUpdate.as_view(), name='compte_update'),
    url(r'^supprimer_compte/(?P<pk>\d+)/$', views.CompteDelete.as_view(), name='compte_delete'),
    url(r'^detail_compte/(?P<pk>\d+)/$', views.CompteDetailView.as_view(), name='detail_compte'),


]

gestion/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Client, TypeClient, Compte
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import StrictButton
from crispy_forms.layout import Layout
from crispy_forms.bootstrap import TabHolder, Tab

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        exclude = ['created_at', 'updated_at', 'ajoute_par']


class TypeClientForm(forms.ModelForm):

    class Meta:
        model = TypeClient
        fields = ['libelle', 'description']


class ClientForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """
        Surcharge de l'initialisation du formulaire
        """
        super().__init__(*args, **kwargs)
        # Tu utilises FormHelper pour customiser ton formulaire
        self.helper = FormHelper()
        # Tu définis l'id et la classe bootstrap de ton formulaire
        self.helper.form_class = 'form-horizontal'
        self.helper.form_id = 'client-form'
        # Tu définis la taille des labels et des champs sur la grille
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-8'
        # Tu crées l'affichage de ton formulaire
        self.helper.layout = Layout(
            # Le formulaire va contenir 3 onglets
            TabHolder(
                # Premier onglet
                Tab(
                    # Label de l'onglet
                    'Général',
                    # Liste des champs du modèle à afficher dans l'onglet
                    'noms',
                    'prenoms',
                    'datenaissance',
                    'photo',
                    # Tu rajoutes un bouton "Suivant"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-right" \
                        aria-hidden="true"></span> %s' % "Suivant",
                        type='button',
                        css_class='btn-warning col-md-offset-9 btnNext',
                    )

                ),
                # Deuxième onglet
                Tab(
                    # Label de l'onglet
                    'Informations',
                    # Liste des champs à afficher
                    'typeclient',
                    'email',
                    'phone',
                    'profession',
                    # Tu rajoutes des boutons "Précédent" et "Suivant"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-left" \
                        aria-hidden="true"></span> %s' % 'Précédent',
                        type='button',
                        css_class='btn-primary btnPrevious',
                    ),
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-right" \
                        aria-hidden="true"></span> %s' % 'Suivant',
                        type='button',
                        css_class='btn-warning col-md-offset-8 btnNext',
                    )
                ),
                # Troisième onglet
                Tab(
                    # Label de l'onglet
                    'Autres',
                    # Liste des champs à afficher dont les champs supplémentaires
                    'adresse',
                    'ville',
                    'nationalite',
                    'quartier',
                    # Tu rajoutes des boutons "Précédent" et "Valider"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-left" \
                        aria-hidden="true"></span> %s' % "Précédent",
                        type='button',
                        css_class='btn-warning btnPrevious',
                    ),
                    StrictButton(
                        '<span class="glyphicon glyphicon-ok" \
                        aria-hidden="true"></span> %s' % "Valider",
                        type='submit',
                        css_class='btn-success col-md-offset-8'
                    )
                ),
            ),
        )

    class Meta:
        # Tu définis le modèle utilisé
        model = Client
        exclude = ['created_at', 'updated_at', 'ajoute_par']



class CompteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """
        Surcharge de l'initialisation du formulaire
        """
        super().__init__(*args, **kwargs)
        # Tu utilises FormHelper pour customiser ton formulaire
        self.helper = FormHelper()
        # Tu définis l'id et la classe bootstrap de ton formulaire
        self.helper.form_class = 'form-horizontal'
        self.helper.form_id = 'compte-form'
        # Tu définis la taille des labels et des champs sur la grille
        self.helper.label_class = 'col-md-2'
        self.helper.field_class = 'col-md-8'
        # Tu crées l'affichage de ton formulaire
        self.helper.layout = Layout(
            # Le formulaire va contenir 3 onglets
            TabHolder(
                # Premier onglet
                Tab(
                    # Label de l'onglet
                    'Compte',
                    # Liste des champs du modèle à afficher dans l'onglet
                    'typecompte',
                    'numero',
                    'ouverture',
                    'cloture',
                    # Tu rajoutes un bouton "Suivant"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-right" \
                        aria-hidden="true"></span> %s' % "Suivant",
                        type='button',
                        css_class='btn-warning col-md-offset-9 btnNext',
                    )

                ),
                # Deuxième onglet
                Tab(
                    # Label de l'onglet
                    'Conditions arrêtées',
                    # Liste des champs à afficher
                    'intitule',
                    'statut',
                    'matricule',
                    'montancartone',
                    # Tu rajoutes des boutons "Précédent" et "Suivant"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-left" \
                        aria-hidden="true"></span> %s' % 'Précédent',
                        type='button',
                        css_class='btn-primary btnPrevious',
                    ),
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-right" \
                        aria-hidden="true"></span> %s' % 'Suivant',
                        type='button',
                        css_class='btn-warning col-md-offset-8 btnNext',
                    )
                ),
                # Troisième onglet
                Tab(
                    # Label de l'onglet
                    'Autres',
                    # Liste des champs à afficher dont les champs supplémentaires
                    'numcpte',
                    'decouvertauto',
                    'debut',
                    'fin',
                    # Tu rajoutes des boutons "Précédent" et "Valider"
                    StrictButton(
                        '<span class="glyphicon glyphicon-arrow-left" \
                        aria-hidden="true"></span> %s' % "Précédent",
                        type='button',
                        css_class='btn-warning btnPrevious',
                    ),
                    StrictButton(
                        '<span class="glyphicon glyphicon-ok" \
                        aria-hidden="true"></span> %s' % "Valider",
                        type='submit',
                        css_class='btn-success col-md-offset-8'
                    )
                ),
            ),
        )

    class Meta:
        # Tu définis le modèle utilisé
        model = Compte
        exclude = ['created_at', 'updated_at', 'ajoute_par']

gestion/views.py
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.forms import ModelForm
from .forms import UserForm, ClientForm, TypeClientForm, CompteForm
import re
from django.db.models import Q

from .models import Client, Compte

# Create your views here.



def index(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('gestion:acceuil')
			else:
				return render(request, 'gestion/pages/index.html', {'error_message': 'Votre compte a été désactivé'})
		else:
			return render(request, 'gestion/pages/index.html', {'error_message': 'Paramètres Invalides'})
	return render(request, 'gestion/pages/index.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('gestion:index')



def acceuil(request):
	return render(request, 'gestion/pages/acceuil.html', {})



# Medicament CRUD
class ClientList(ListView):
	model = Client

class ClientCreate(CreateView):
	model = Client
	form_class = ClientForm
	success_url = reverse_lazy('gestion:client_list')

class ClientUpdate(UpdateView):
	model = Client
	form_class = ClientForm
	success_url = reverse_lazy('gestion:client_list')

class ClientDelete(DeleteView):
	model = Client
	success_url = reverse_lazy('gestion:client_list')

class ClientDetailView(DetailView):

    model = Client
    success_url = reverse_lazy('gestion:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



# Medicament CRUD
class CompteList(ListView):
	model = Compte

class CompteCreate(CreateView):
	model = Compte
	form_class = CompteForm
	success_url = reverse_lazy('gestion:compte_list')

class CompteUpdate(UpdateView):
	model = Compte
	form_class = CompteForm
	success_url = reverse_lazy('gestion:compte_list')

class CompteDelete(DeleteView):
	model = Compte
	success_url = reverse_lazy('gestion:compte_list')

class CompteDetailView(DetailView):

    model = Compte
    success_url = reverse_lazy('gestion:compte_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

gestion/templates/gestion/pages/base.html
<!DOCTYPE html>
{% load static %}
<html>
    
<!-- Mirrored from themesdesign.in/admiry/red/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 01 Nov 2019 13:21:30 GMT -->
<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
        <title>{% block title %}{% endblock %}</title>
        <meta content="Admin Dashboard" name="description" />
        <meta content="ThemeDesign" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <link rel="shortcut icon" href="{% static 'gestion/assets/images/favico1.ico' %}">

        <!--Morris Chart CSS -->
        <link rel="stylesheet" href="{% static 'gestion/assets/plugins/morris/morris.css' %}">

        <link href="{% static 'gestion/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'gestion/assets/css/icons.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'gestion/assets/css/style.css' %}" rel="stylesheet" type="text/css">

    </head>


    <body class="fixed-left">

        <!-- Loader -->
        <div id="preloader"><div id="status"><div class="spinner"></div></div></div>

        <!-- Begin page -->
        <div id="wrapper">

            <!-- ========== Left Sidebar Start ========== -->
            {% include 'gestion/pages/side-menu.html' %}
            <!-- Left Sidebar End -->

            <!-- Start right Content here -->

            <div class="content-page">
                <!-- Start content -->
                <div class="content">

                    <!-- Top Bar Start -->
                    {% include 'gestion/pages/topbar.html' %}
                    <!-- Top Bar End -->

                    {% block content %}{% endblock %}

                </div> <!-- content -->

                <footer class="footer">
                    © 2019 - {% block title_footer %}{% endblock %} - MicroFinance.
                </footer>

            </div>
            <!-- End Right content here -->

        </div>
        <!-- END wrapper -->


        <!-- jQuery  -->
        <script src="{% static 'gestion/assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'gestion/assets/js/tether.min.js' %}"></script><!-- Tether for Bootstrap -->
        <script src="{% static 'gestion/assets/js/popper.min.js' %}"></script>
        <script src="{% static 'gestion/assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'gestion/assets/js/modernizr.min.js' %}"></script>
        <script src="{% static 'gestion/assets/js/detect.js' %}"></script>
        <script src="{% static 'gestion/assets/js/fastclick.js' %}"></script>
        <script src="{% static 'gestion/assets/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'gestion/assets/js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'gestion/assets/js/waves.js' %}"></script>
        <script src="{% static 'gestion/assets/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'gestion/assets/js/jquery.scrollTo.min.js' %}"></script>

        <!--Morris Chart-->
        <script src="{% static 'assets/plugins/morris/morris.min.js' %}"></script>
        <script src="{% static 'assets/plugins/raphael/raphael-min.js' %}"></script>

        <script src="{% static 'assets/pages/dashborad.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'gestion/assets/js/app.js' %}"></script>

        

    </body>

<!-- Mirrored from themesdesign.in/admiry/red/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 01 Nov 2019 13:21:30 GMT -->
</html>

gestion/templates/gestion/pages/client_form.html
{% extends 'gestion/pages/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Créer un Client{% endblock %}

{% block content %}

    <div class="page-content-wrapper ">

        <div class="container-fluid">


            <div class="card">
                <div class="card-body">

                    <h3 class="text-center mt-0 m-b-15">
                        <a href="" class="logo logo-admin"><!--img src="" height="54" alt="logo"--></a>
                    </h3>

                    <h4 class="text-muted text-center font-18"><b>Créer un Client</b></h4>

                    <div class="p-3">
                        {% crispy form %}
                    </div>

                </div>
            </div>
            
        </div>

    </div>










{% endblock %}


{% block title_footer %}Créer un Client{% endblock %}

gestion/templates/gestion/pages/client_list.html
{% extends 'gestion/pages/base.html' %}

{% block title %}Liste des Clients{% endblock %}

{% block content %}


            <div class="page-content-wrapper ">

                    <div class="box-footer">
                        <a href="{% url 'gestion:client_create' %}" class="btn btn-primary">Ajouter</a>
                    </div>


                        <div class="row">

                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">
                                            <h4 class="mt-0 m-b-15 header-title"> <span class="badge badge-primary"></span>Liste des Clients </h4>
                                            <div class="table-responsive">
                                                <table class="table table-hover m-b-0">
                                                    <thead>
                                                    <tr>
                                                        <th>Noms</th>
                                                        <th>Prénoms</th>
                                                        <th>Adresse</th>
                                                        <th>Téléphone</th>
                                                        <th>Type Client</th>
                                                        <th>Date Création</th>
                                                        <th>Actions</th>
                                                    </tr>

                                                    </thead>
                                                    <tbody>
                                                    {% for client in client_list %}
                                                      <tr>
                                                        <td>
                                                          <a href="{% url 'gestion:client_update' client.id %}">
                                                           {{ client.id }} 
                                                          </a>
                                                        </td>
                                                        <td>{{ client.noms }}</td>
                                                        <td>{{ client.prenoms }}</td>
                                                        <td>{{ client.adresse }}</td>
                                                        <td>{{ client.phone }}</td>
                                                        <td>{{ client.typeclient }}</td>
                                                        <td>{{ client.description }}</td>
                                                        <td>
                                                          <div class="btn-group" role="group" aria-label="...">
                                                            <a href="{% url 'gestion:client_update' client.id %}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                            <a href="{% url 'gestion:client_delete' client.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                                          </div>
                                                        </td>
                                                      </tr>
                                                   {% endfor %}

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- end row -->


                    </div> <!-- Page content Wrapper --> 










{% endblock %}


{% block title_footer %}Liste des Clients{% endblock %}

gestion/templates/gestion/pages/side-menu.html
            {% load static %}
            <!-- ========== Left Sidebar Start ========== -->
            <div class="left side-menu">
                <button type="button" class="button-menu-mobile button-menu-mobile-topbar open-left waves-effect">
                    <i class="ion-close"></i>
                </button>

                <!-- LOGO -->
                <div class="topbar-left">
                    <div class="text-center">
                        <!--<a href="index.html" class="logo">Admiry</a>-->
                        <a href="" class="logo"><!--img src="assets/images/log3.PNG" height="42" alt="logo"--></a>
                    </div>
                </div>

                <div class="sidebar-inner slimscrollleft">

                    <div class="user-details">
                        <div class="text-center">
                            <img src="{% static 'gestion/assets/images/users/avatar-1.jpg' %}" alt="" class="rounded-circle">
                        </div>
                        <div class="user-info">
                            <h4 class="font-16">{{ user.username }}</h4>
                            <span class="text-muted user-status"><i class="fa fa-dot-circle-o text-success"></i> En ligne</span>
                        </div>
                    </div>

                    <div id="sidebar-menu">
                        <ul>
                            <li>
                                <a href="{% url 'gestion:acceuil' %}" class="waves-effect">
                                    <i class="mdi mdi-view-dashboard"></i>
                                    <span> Dashboard <span class="badge badge-primary pull-right"></span></span>
                                </a>
                            </li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-buffer"></i> <span>Gestion des Clients </span> </a>
                                <ul class="list-unstyled">
                                    <li><a href="{% url 'gestion:client_list' %}"><i class="mdi mdi-web"></i>Liste des Clients</a></li>
                                </ul>
                            </li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-wallet"></i> <span> Comptes </span> </a>
                                <ul class="list-unstyled">
                                    <li><a href="{% url 'gestion:compte_list' %}"><i class="mdi mdi-wallet-membership"></i>Liste des Comptes</a></li>
                                </ul>
                            </li>


                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-verified"></i><span> Opérations </span></a>
                                <ul class="list-unstyled">
                                    <!--li><a href="pages-invoice.html">Invoice</a></li-->
                                    <li><a href=""><i class="mdi mdi-account-key"></i>Dépôts</a></li>
                                    <li><a href=""><i class="mdi mdi-account-multiple"></i>Retraits</a></li>
                                </ul>
                            </li>



                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-tag"></i><span> Services </span></a>
                                <ul class="list-unstyled">
                                    <!--li><a href="pages-invoice.html">Invoice</a></li-->
                                    <li><a href=""><i class="mdi mdi-account-key"></i>Virement</a></li>
                                    <li><a href=""><i class="mdi mdi-account-multiple"></i>Prêt</a></li>
                                    <li><a href=""><i class="mdi mdi-tag"></i>MAD</a></li>
                                    <li><a href=""><i class="mdi mdi-verified"></i>RDC</a></li>
                                </ul>
                            </li>


                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-account-key"></i><span> Communication </span></a>
                                <ul class="list-unstyled">
                                    <!--li><a href="pages-invoice.html">Invoice</a></li-->
                                    <li><a href=""><i class="mdi mdi-account-key"></i>Notifications</a></li>
                                    <li><a href=""><i class="mdi mdi-account-multiple"></i>Aide</a></li>
                                    <li><a href="{% url 'gestion:logout' %}"><i class="mdi mdi-stop-circle"></i>Déconnexion</a></li>
                                </ul>
                            </li>



                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div> <!-- end sidebarinner -->
            </div>
            <!-- Left Sidebar End -->

gestion/templates/gestion/pages/topbar.html
                    {% load static %}
                    <!-- Top Bar Start -->
                    <div class="topbar">

                        <nav class="navbar-custom">

                            <ul class="list-inline float-right mb-0">
                                <li class="list-inline-item dropdown notification-list">
                                    <a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#" role="button"
                                       aria-haspopup="false" aria-expanded="false">
                                        <i class="ion-ios7-bell noti-icon"></i>
                                        <span class="badge badge-success noti-icon-badge">3</span>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg">
                                        <!-- item-->
                                        <div class="dropdown-item noti-title">
                                            <h5><span class="badge badge-danger float-right">87</span>Notification</h5>
                                        </div>

                                        <!-- item-->
                                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                                            <div class="notify-icon bg-primary"><i class="mdi mdi-cart-outline"></i></div>
                                            <p class="notify-details"><b>Votre paiement a été effectué</b><small class="text-muted">Vous serez notifié par email et sms.</small></p>
                                        </a>

                                        <!-- item-->
                                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                                            <div class="notify-icon bg-primary"><i class="mdi mdi-message"></i></div>
                                            <p class="notify-details"><b>Votre solde CASHBACK est vide</b><small class="text-muted">Essayer de faire le maximum de paiements SUMBA pour renflouer votre CASHBACK</small></p>
                                        </a>


                                        <!-- All-->
                                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                                            Voir Tout
                                        </a>

                                    </div>
                                </li>

                                <li class="list-inline-item dropdown notification-list">
                                    <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown" href="#" role="button"
                                       aria-haspopup="false" aria-expanded="false">
                                        <img src="{% static 'gestion/assets/images/users/avatar-1.jpg' %}" alt="user" class="rounded-circle">
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                                        <a class="dropdown-item" href="#"><i class="mdi mdi-account-circle m-r-5 text-muted"></i>Mon Profil</a>
                                        <a class="dropdown-item" href="#"><span class="badge badge-success pull-right">5</span><i class="mdi mdi-settings m-r-5 text-muted"></i> Paramètres</a>
                                        <a class="dropdown-item" href="{% url 'gestion:logout' %}"><i class="mdi mdi-logout m-r-5 text-muted"></i> Déconnexion</a>
                                    </div>
                                </li>

                            </ul>

                            <ul class="list-inline menu-left mb-0">
                                <li class="list-inline-item">
                                    <button type="button" class="button-menu-mobile open-left waves-effect">
                                        <i class="ion-navicon"></i>
                                    </button>
                                </li>
                                <li class="hide-phone list-inline-item app-search">
                                    <h3 class="page-title">Dashboard</h3>
                                </li>
                            </ul>

                            <div class="clearfix"></div>

                        </nav>

                    </div>
                    <!-- Top Bar End -->